from __future__ import annotations


def theta(L: float, r: float) -> float:
    ...

def d_theta(L: float, r: float) -> float:
    ...

def _polygon_fill(r_coords, c_coords):
    """
    Rasterize a polygon given row (r) and column (c) vertex coordinates,
    returning (rr, cc) arrays of filled pixel coordinates.

    Equivalent in spirit to skimage.draw.polygon
    """

def _skeletonize(image):
    """
    Topological skeleton of a binary image via the Zhang-Suen thinning
    algorithm.

    Functionally replaces skimage.morphology.skeletonize.
    """

def _skeleton_to_paths(skeleton):
    """
    Trace a thinned (1px-wide) binary skeleton into a list of polylines,
    each a list of (row, col) float coordinates.
    """

def _normalize(vx, vy):
    ...

def _line_intersect(p1, p2, p3, p4):
    """Intersection point of infinite lines through (p1,p2) and (p3,p4), or None if parallel."""

def _polygon_buffer(points, distance, arc_segments=8):
    ...

# This file was generated by stubgen-pyx v0.2.15 from /home/grapefru14/Documents/Blaze-Sudio/BlazeSudio/utils/wrap/_core.pyx