[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Blaze-Sudio"
version = "3.2.0"
description = "This is a really cool game/physics/graphics/application engine with everything written from scratch and is much more efficient than existing things!"
readme = "README.md"
license = "MIT"
authors = [
    {name = "Tsunami014", email = "tsunami014@duck.com"}
]
maintainers = [
    {name = "Tsunami014", email = "tsunami014@duck.com"}
]
keywords = ["Python", "games", "engine"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Build Tools",
    "Operating System :: Unix",
    "Operating System :: Microsoft :: Windows"
]
# Development Status options:
# 1 - Planning
# 2 - Pre-Alpha
# 3 - Alpha
# 4 - Beta
# 5 - Production/Stable
# 6 - Mature
# 7 - Inactive

dependencies = [
    "numpy",
    "pillow",
    "freetype-py",
    "pyperclip",
]

requires-python = ">= 3.11"

[project.urls]
Homepage = "https://github.com/Tsunami014/Blaze-Sudio"
Download = "https://github.com/Tsunami014/Blaze-Sudio/archive/refs/tags/v3.2.0.tar.gz"
Documentation = "https://tsunami014.gitbook.io/blaze-sudios/"
Repository = "https://github.com/Tsunami014/Blaze-Sudio"
Issues = "https://github.com/Tsunami014/Blaze-Sudio/issues"

[tool.setuptools.packages.find]
exclude = [
    "BlazeSudio.speed.setup",
    "BlazeSudio.speed.time"
]

[tool.setuptools.package-data]
"BlazeSudio" = [
    "ldtk/internal-icons.png",

    "**/*.pyi",
    "**/*.so", "**/*.pyd"
]
