from __future__ import annotations

import numpy as cnp

__cimport_types__ = [cnp.ndarray]

def fill_arr(arr: cnp.ndarray, col: cnp.ndarray):
    ...

# This file was generated by stubgen-pyx v0.2.13 from /home/grapefru14/Documents/Blaze-Sudio/BlazeSudio/graphicsCore/_misc/init.pyx